[package]
name = "bulin_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["wgpu", "highlighter", "tokio", "debug", "image", "advanced"] }

tokio = { version = "1.0", features = ["fs"] }
iced_wgpu = "0.13.5"
glam = { version = "0.25.0", features = ["bytemuck"] }
bytemuck = "1.21.0"
rfd = "0.13"
rand = "0.8.5"
image = "0.25.5"
once_cell = "1.20.2"
two-face = { version = "0.4.2", features = ["syntect-default-onig"] }
