[package]
name = "bulin"
version = "0.1.0"
edition = "2024"


[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
anyhow = "1.0.98"
eframe = { version = "0.32.0", features = ["wgpu"] }
egui = { version = "0.32.0", features = ["callstack", "default", "log"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["time"] }
# Same version as egui
wgpu = { version = "25.0", features = ["vulkan", "webgl"] }

# WebAssembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
log = "0.4"
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "native"
path = "src/main.rs"

[[bin]]
name = "web"
path = "src/web.rs"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
