name: Rust CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [native, wasm32-unknown-unknown]
        mode: [debug, release]
        include:
          - target: native
            target_flag: ""
          - target: wasm32-unknown-unknown
            target_flag: "--target wasm32-unknown-unknown"
          - mode: debug
            mode_flag: ""
            test_flag: ""
          - mode: release
            mode_flag: "--release"
            test_flag: "--release"

    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: wasm32-unknown-unknown

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}-${{ matrix.mode }}

      - name: Build ${{ matrix.mode }} for ${{ matrix.target }}
        run: cargo build ${{ matrix.mode_flag }} ${{ matrix.target_flag }}

      - name: Run tests ${{ matrix.mode }} for ${{ matrix.target }}
        if: matrix.target == 'native'
        run: cargo test --all ${{ matrix.test_flag }}
